Adds initial docstrings for ´std/vec´
rtulip/haystack pull request #205
Opened 2023-04-07 05:17 UTC by wfzyx

Refers: #141 

I had no idea what would be a good format to start with, so I tried a mix between rust/dotnet.

This draft is just a sanity check to see if this fits, and I'll expand the PR based on comments before pushing it to a proper review.

Obs:  The reason why this is pointing to master instead of release as pointed about on the contribute.md is just to keep the diff short, as the release is not rebased.

2023-04-07 12:33 UTC, rtulip commented
Content looks great, thanks for getting this started!

A few thoughts I do have:
1. Since some functions don't bind their inputs to an identifier, the documentation format should probably support that.
Maybe something like:
```
// Inputs:
// - T (value): the value to add to the vector
// - *Vec<T> (self): a mutable reference to the vector to add the value to
```
2. If each function had just a small code snippet formatted for Markdown, that would be great.
eg:
```
//```
// Vec.new::<u64> as [mut v]
// 12345 *v Vec.push
// 0 &v Vec.at Option.unwrap 12345 == assert
//```
```

I'll also sync the release branch, and get you to merge through there.

Thanks again for offering to help! You'll get to be the first new contributor!

2023-04-07 23:32 UTC, wfzyx commented
Did a new revision, care to check if it is more aligned with what you had in mind? I do believe there is errors on the examples, specially related to pointer semantics

2023-04-08 13:01 UTC, rtulip requested changes
Looks pretty good. A few small changes to the examples. Which is totally fine :+1:

2023-04-08 13:01 UTC, rtulip commented on std/vec.hay
> +    // 12345 v Vec.pop Option.unwrap 12345 == assert
Close. We don't need to repeat `12345`.
We also need to give a mutable pointer to the vec as well with `*v` instead of `v`

``` 
12345 *v Vec.push
*v Vec.pop
Option.unwrap 12345 == assert
```

2023-04-08 13:01 UTC, rtulip commented on std/vec.hay
> +    // 0 &v Vec.get Option.unwrap == 10 assert
2 things here:
1. `get` returns a reference, which we need to dereference in order to compare to the value.
2. `==` operator comes after the arguments

```
0 &v Vec.get Option.unwrap @ 10 == assert
```

2023-04-08 13:01 UTC, rtulip commented on std/vec.hay
> +    // *v 0 Vec.get_mut Option.unwrap 12345 == assert
Very close, pointer and index are in the wrong order, and need to read from the pointer:
```
0 *v Vec.get_mut Option.unwrap @ 12345 == assert
```

Could also be good to provide an example of reading writing to the pointer:
```
0 *v Vec.get_mut Option.unwrap 54321 !
0 &v Vec.at Option.unwrap 54321 == assert
```

2023-04-08 13:01 UTC, rtulip commented on std/vec.hay
> +    // &v Vec.last Option.unwrap 456 == assert
Again, very close. Just need to read with the `@` operator:
```
&v Vec.last Option.unwrap @ 456 == assert
```

2023-04-08 13:01 UTC, rtulip commented on std/vec.hay
> +    // not sure how to do this one :(
Here you go
```
Vec.new::<u64> as [v]
&v Vec.capacity 8 == assert // default capacity is 8 unfortunately :(
```

2023-04-08 13:01 UTC, rtulip commented on std/vec.hay
> +    // [1 2 3 4] 3 Vec.contains true == assert
Unfortunately, this doesn't quite work. `[1 2 3 4]` is a tuple, not a `Vec`.

```
Vec.new::<u64> as [mut v]
123 *v Vec.push

321 &v Vec.contains false == assert
123 &v Vec.contains true == assert
```

2023-04-08 13:01 UTC, rtulip commented on std/vec.hay
> +    // &v Vec.last Option.unwrap 123 == assert
Again, just need to dereference with `@`, since `Vec.last` returns an Optional reference.

2023-04-09 23:07 UTC, wfzyx commented on std/vec.hay
> +    // 0 &v Vec.get Option.unwrap == 10 assert
I'm getting

`[input.hay:10:32] Error: Type Error: Expected to find T in {}`

on the last line of (with or without @):

```
fn main(){
    Vec.new::<u64> as [mut v]
    10 *v Vec.push
    20 *v Vec.push
    30 *v Vec.push
    40 *v Vec.push
    0 &v Vec.get Option.unwrap @ 10 == assert
    3 &v Vec.get Option.unwrap @ 40 == assert
    5 &v Vec.get Option.unwrap Option.None == assert
}
```

2023-04-09 23:08 UTC, wfzyx commented on std/vec.hay
> +    // *v 0 Vec.get_mut Option.unwrap 12345 == assert
Couldn't make the ! to work

```
fn main(){
    Vec.new::<u64> as [mut v]
    12345 *v Vec.push
    0 *v Vec.get_mut Option.unwrap @ 12345 == assert
    0 *v Vec.get_mut Option.unwrap 54321 !
    0 &v Vec.at Option.unwrap 54321 == assert
}
```

[input.hay:5:42] Error: Type Error: Cannot resolve *T from u64

2023-04-09 23:27 UTC, wfzyx commented on std/vec.hay
> +    // not sure how to do this one :(
Thank you! :D

2023-04-09 23:49 UTC, wfzyx commented on std/vec.hay
> +    // 0 &v Vec.get Option.unwrap == 10 assert
Even typecasting it still complains

```
fn main(){
    Vec.new::<u64> as [mut v]
    10 *v Vec.push
    20 *v Vec.push
    30 *v Vec.push
    40 *v Vec.push
    0 &v Vec.get Option.unwrap @ 10 == assert
    3 &v Vec.get Option.unwrap @ 40 == assert
    5 &v Vec.get Option.unwrap @ Option.None::<&u64> == assert
}
```

```
[input.hay:9:53] Error: Type Error: Invalid inputs for `==`
    [Note]: Expected one of 7 signatures:
    [Note]:   [u64, u64]
    [Note]:   [u8, u8]
    [Note]:   [bool, bool]
    [Note]:   [char, char]
    [Note]:   [*T, *T]
    [Note]:   [&T, &T]
    [Note]:   [E, E] where E is an enum
    [Note]: Found:
    [Note]:   [u64, Option<u64>]
```
I tried unwraping it, but then it complains about unwraping a none type

2023-04-10 00:20 UTC, rtulip commented on std/vec.hay
> +    // 0 &v Vec.get Option.unwrap == 10 assert
Oh yeah. I'd change the last check to this:

```
5 &v Vec.get Option.take_is_none assert
```

2023-04-10 00:23 UTC, rtulip commented on std/vec.hay
> +    // *v 0 Vec.get_mut Option.unwrap 12345 == assert
My bad, had the order of the pointer and value wrong for `! `. Try:

```
0 *v Vec.get_mut Option.unwrap 54321 swap ! 
```

2023-04-10 00:56 UTC, wfzyx commented on std/vec.hay
> +    // 0 &v Vec.get Option.unwrap == 10 assert
`[input.hay:9:18] Error: Type Error: Unrecognized word Option.take_is_none`

2023-04-10 01:00 UTC, wfzyx commented on std/vec.hay
> +    // 0 &v Vec.get Option.unwrap == 10 assert
I guess it should be `Option.is_none` ?

Something close to this

`5 &v Vec.get Option.is_none::<u64> assert`

2023-04-10 01:15 UTC, wfzyx commented
Everything fixed, tested with the compiler.

I've added the take_is_none implementation on this PR, if that is not ok, I'll move it to another one

2023-04-10 22:50 UTC, rtulip approved these changes
Looks Great!

2023-04-15 12:49 UTC, merged